//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataKaryawanDekstop
{
    using System;
    using System.Collections.Generic;
    
    public partial class Karyawan
    {
        public decimal NIK { get; set; }
        public string Nama_Lengkap { get; set; }
        public string Jenis_Kelamin { get; set; }
        public Nullable<System.DateTime> Tanggal_Lahir { get; set; }
        public string Alamat { get; set; }
        public string Negara { get; set; }
    }
}
